#!/usr/bin/env tsx
/**
 * Generate docs/mcp-env-variables.md from ENV_VAR_DOCS in src/envReference.ts
 * (#599).
 *
 * The inventory in envReference.ts is the single source of truth: it states
 * each MCP environment variable's name, description, default, accepted
 * values, and the module that reads it — with defaults imported from the
 * owning module's exported constants, so a default that changes in code
 * changes the reference in the same PR. This script serialises the inventory
 * into a Markdown table operators can read without opening the source.
 *
 * Usage:
 *   pnpm --filter @zentrixpay/mcp generate-env-reference
 *   # or from mcp/
 *   pnpm generate-env-reference
 *
 * The command is idempotent — running it twice produces identical output.
 * Commit the generated file so CI and contributors always have it without
 * running the command first.
 *
 * A staleness guard in src/envReference.test.ts verifies the committed file
 * matches ENV_VAR_DOCS; a PR that adds a variable without regenerating fails
 * the test suite.
 */

import { writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { ENV_VAR_DOCS } from "../src/envReference.js";

const here = dirname(fileURLToPath(import.meta.url));
const docsDir = join(here, "..", "..", "docs");
const outPath = join(docsDir, "mcp-env-variables.md");

/** Escape pipe characters inside a Markdown table cell. */
function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function generate(): string {
  const lines: string[] = [
    "# MCP Environment Variables Reference",
    "",
    "<!-- Generated by scripts/generate-env-reference.ts — do not edit by hand. -->",
    "<!-- Run `pnpm --filter @zentrixpay/mcp generate-env-reference` to regenerate. -->",
    "",
    "Every environment variable the ZentrixPay MCP server reads, generated from",
    "[`mcp/src/envReference.ts`](../mcp/src/envReference.ts) — the single source",
    "of truth for names, defaults, and accepted values. Defaults are imported",
    "from the module that enforces them, so this page cannot drift from what",
    "the code actually applies.",
    "",
    "For the server-side (non-MCP) variables, see",
    "[environment-variables.md](environment-variables.md), which remains the",
    "prose-level explanation of deployment configuration.",
    "",
    `**${ENV_VAR_DOCS.length} variables** as of last generation.`,
    "",
    "---",
    "",
    "| Variable | Description | Default | Accepted values | Source |",
    "| --- | --- | --- | --- | --- |",
  ];

  for (const doc of ENV_VAR_DOCS) {
    const values = doc.values ? doc.values.map(escapeCell).join(" · ") : "—";
    lines.push(
      `| \`${doc.name}\` | ${escapeCell(doc.description)} | ${escapeCell(doc.default)} | ${values} | \`${doc.source}\` |`,
    );
  }

  lines.push(
    "",
    "---",
    "",
    "_This file was generated from `mcp/src/envReference.ts` —",
    `${ENV_VAR_DOCS.length} variables._`,
    "",
  );

  return lines.join("\n");
}

function main(): void {
  console.log("ZentrixPay MCP — generating env var reference docs");
  mkdirSync(docsDir, { recursive: true });
  const content = generate();
  writeFileSync(outPath, content, "utf-8");
  console.log(`  wrote ${outPath}`);
  console.log(`\n✓ Env var reference written (${ENV_VAR_DOCS.length} variables)`);
}

main();
