/**
 * Renderers for the generated tool documentation (#680).
 *
 * Two committed files are derived from `TOOL_DEFINITIONS` in `tools.ts`:
 *
 *   - `docs/mcp-tool-reference.md`, the grouped reference table integrators read
 *   - `mcp/GENERATED_MCP_TOOL_SUMMARY.md`, the flat summary shipped with the package
 *
 * Both are produced by `scripts/generate-tool-docs.ts`, which also has a
 * `--check` mode that CI runs: it renders the same content, formats it the way
 * the repository's commit hook would, and fails when a committed file differs.
 * Keeping the renderers here (pure, no I/O) lets the unit tests assert the same
 * freshness property without spawning the script.
 *
 * Why formatting is part of the contract: `lint-staged` runs `prettier --write`
 * on every staged Markdown file, so raw generator output never survives a
 * commit. A byte-for-byte check against unformatted output would report every
 * committed file as stale forever; the check therefore compares against
 * prettier-formatted output and the generator writes that form as well.
 */

import type { ToolDefinition } from "./tools.js";

/** Paths are relative to the repository root. */
export const TOOL_REFERENCE_PATH = "docs/mcp-tool-reference.md";
export const TOOL_SUMMARY_PATH = "mcp/GENERATED_MCP_TOOL_SUMMARY.md";

/** Marker every generated file carries; `toolDescriptions.test.ts` asserts it. */
export const GENERATED_MARKER = "Generated by scripts/generate-tool-docs.ts";

export const REGENERATE_COMMAND = "pnpm --filter @zentrixpay/mcp generate-tool-docs";

/**
 * Classify a tool into a functional group so the reference page is scannable
 * rather than a single flat list.
 */
export function groupOf(name: string): string {
  if (["zentrixpay_setup_wallet", "zentrixpay_wallet_info", "zentrixpay_import_wallet"].includes(name))
    return "Wallet";
  if (["zentrixpay_use_profile", "zentrixpay_list_profiles"].includes(name)) return "Profiles";
  if (["zentrixpay_browse", "zentrixpay_search", "zentrixpay_preview"].includes(name))
    return "Catalog";
  if (
    [
      "zentrixpay_register",
      "zentrixpay_publish",
      "zentrixpay_publish_status",
      "zentrixpay_buy",
      "zentrixpay_buy_lease",
      "zentrixpay_lease_status",
    ].includes(name)
  )
    return "Publishing & Buying";
  if (
    [
      "zentrixpay_register_onchain",
      "zentrixpay_update_metadata",
      "zentrixpay_set_price",
      "zentrixpay_set_tags",
      "zentrixpay_transfer_ownership",
      "zentrixpay_set_listed",
    ].includes(name)
  )
    return "On-chain Management";
  if (
    [
      "zentrixpay_registry_info",
      "zentrixpay_registry_lookup",
      "zentrixpay_registry_list",
      "zentrixpay_registry_health",
      "zentrixpay_check_consistency",
      "zentrixpay_check_bindings",
      "zentrixpay_tx_status",
    ].includes(name)
  )
    return "Registry & Diagnostics";
  if (["zentrixpay_purchase_history", "zentrixpay_export_receipts"].includes(name)) return "Receipts";
  if (
    [
      "zentrixpay_backup_state",
      "zentrixpay_restore_state",
      "zentrixpay_reset",
      "zentrixpay_check_state_permissions",
    ].includes(name)
  )
    return "State Management";
  if (
    [
      "zentrixpay_agent_status",
      "zentrixpay_network_profile",
      "zentrixpay_metrics",
      "zentrixpay_rotate_publisher_key",
      "zentrixpay_verify_install",
      "zentrixpay_debug_bundle",
    ].includes(name)
  )
    return "Operations";
  return "Other";
}

const GROUP_ORDER = [
  "Wallet",
  "Profiles",
  "Catalog",
  "Publishing & Buying",
  "On-chain Management",
  "Registry & Diagnostics",
  "Receipts",
  "State Management",
  "Operations",
  "Other",
];

/** Escape pipe characters inside a Markdown table cell. */
function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

/** The grouped reference page (`docs/mcp-tool-reference.md`). */
export function renderToolReference(tools: readonly ToolDefinition[]): string {
  const groups = new Map<string, ToolDefinition[]>();
  for (const tool of tools) {
    const g = groupOf(tool.name);
    if (!groups.has(g)) groups.set(g, []);
    groups.get(g)!.push(tool);
  }

  const lines: string[] = [
    "# MCP Tool Reference",
    "",
    `<!-- ${GENERATED_MARKER} — do not edit by hand. -->`,
    `<!-- Run \`${REGENERATE_COMMAND}\` to regenerate. -->`,
    "",
    "Every tool the ZentrixPay MCP server advertises via ListTools, grouped by",
    "function. Descriptions come directly from",
    "[`mcp/src/tools.ts`](../mcp/src/tools.ts) — the single source of truth for",
    "what agent clients receive.",
    "",
    "For argument contracts and validation rules see",
    "[mcp-tool-arguments.md](mcp-tool-arguments.md).",
    "For structured JSON results (`structuredContent` + `outputSchema`) see",
    "[mcp-structured-output.md](mcp-structured-output.md).",
    "For client installation and configuration see",
    "[mcp-client-configs.md](mcp-client-configs.md).",
    "",
    `**${tools.length} tools** as of last generation.`,
    "",
    "---",
    "",
  ];

  for (const groupName of GROUP_ORDER) {
    const members = groups.get(groupName);
    if (!members || members.length === 0) continue;

    lines.push(`## ${groupName}`, "");
    lines.push("| Tool | Description | Structured |");
    lines.push("| --- | --- | --- |");
    for (const tool of members) {
      const structured = tool.outputSchema ? "yes" : "text only";
      lines.push(`| \`${tool.name}\` | ${escapeCell(tool.description)} | ${structured} |`);
    }
    lines.push("");
  }

  lines.push("---", "");
  lines.push(`_This file was generated from \`mcp/src/tools.ts\` — ${tools.length} tools._`, "");

  return lines.join("\n");
}

/** The flat summary shipped in the package (`mcp/GENERATED_MCP_TOOL_SUMMARY.md`). */
export function renderToolSummary(tools: readonly ToolDefinition[]): string {
  const lines: string[] = [
    "# MCP Tool Summary (generated)",
    "",
    `<!-- ${GENERATED_MARKER}. Do not edit by hand. -->`,
    `<!-- Run \`${REGENERATE_COMMAND}\` to regenerate. -->`,
    "",
    "This file is a generated, human-readable summary of the MCP tool surface (ListTools). It is scoped to the `mcp/` package and intended as a quick reference for integrators and reviewers.",
    "",
    `Generated from \`mcp/src/tools.ts\` (${tools.length} tools).`,
    "",
    "## Tools",
    "",
  ];
  for (const tool of tools) {
    lines.push(`- \`${tool.name}\`: ${tool.description}`);
  }
  lines.push(
    "",
    "## Notes",
    "",
    "- This file is generated from the tool metadata and is intended as documentation only. For authoritative schemas and input validation, see `mcp/src/tools.ts` and `mcp/src/validation.ts`.",
    "- CI fails when this file or `docs/mcp-tool-reference.md` no longer matches `TOOL_DEFINITIONS` (`pnpm --filter @zentrixpay/mcp check-tool-docs`). Run the command above after changing a tool.",
    "",
  );
  return lines.join("\n");
}

export interface ToolDocTarget {
  /** Path relative to the repository root. */
  readonly relativePath: string;
  readonly render: (tools: readonly ToolDefinition[]) => string;
}

/** Every generated file, in the order the script reports them. */
export const TOOL_DOC_TARGETS: readonly ToolDocTarget[] = [
  { relativePath: TOOL_REFERENCE_PATH, render: renderToolReference },
  { relativePath: TOOL_SUMMARY_PATH, render: renderToolSummary },
];

export type ToolDocFreshness = "fresh" | "stale" | "missing";

/** Compare a committed file against what the generator would write. */
export function toolDocFreshness(committed: string | null, expected: string): ToolDocFreshness {
  if (committed === null) return "missing";
  return committed === expected ? "fresh" : "stale";
}
